package pl.coderslab.tydzien2.z2parametryzowanieTestówEnum;

public enum Numbers {

    ONE(1, false),
    TWO(2, true),
    THREE(3, true),
    FOUR(4, false),
    FIVE(5, true),
    SIX(6, false),
    SEVEN(7, true),
    EIGHT(8, false),
    NINE(9, false),
    TEN(10, false),
    ELEVEN(11, true),
    TWELVE(12, false),
    THIRTEEN(13, true),
    FOURTEEN(14, false),
    FIFTEEN(15, false),
    SIXTEEN(16, false),
    SEVENTEEN(17, true),
    EIGHTEEN(18, false),
    NINETEEN(19, true),
    TWENTY(20, false),
    TWENTY_ONE(21, false),
    TWENTY_TWO(22, false),
    TWENTY_THREE(23, true),
    TWENTY_FOUR(24, false),
    TWENTY_FIVE(25, false),
    TWENTY_SIX(26, false),
    TWENTY_SEVEN(27, false),
    TWENTY_EIGHT(28, false),
    TWENTY_NINE(29, true),
    THIRTY(30, false),
    THIRTY_ONE(31, true),
    THIRTY_TWO(32, false),
    THIRTY_THREE(33, false),
    THIRTY_FOUR(34, false),
    THIRTY_FIVE(35, false),
    THIRTY_SIX(36, false),
    THIRTY_SEVEN(37, true),
    THIRTY_EIGHT(38, false),
    THIRTY_NINE(39, false),
    FORTY(40, false),
    FORTY_ONE(41, true),
    FORTY_TWO(42, false),
    FORTY_THREE(43, true),
    FORTY_FOUR(44, false),
    FORTY_FIVE(45, false),
    FORTY_SIX(46, false),
    FORTY_SEVEN(47, true),
    FORTY_EIGHT(48, false),
    FORTY_NINE(49, false),
    FIFTY(50, false),
    FIFTY_ONE(51, false),
    FIFTY_TWO(52, false),
    FIFTY_THREE(53, true),
    FIFTY_FOUR(54, false),
    FIFTY_FIVE(55, false),
    FIFTY_SIX(56, false),
    FIFTY_SEVEN(57, false),
    FIFTY_EIGHT(58, false),
    FIFTY_NINE(59, true),
    SIXTY(60, false),
    SIXTY_ONE(61, true),
    SIXTY_TWO(62, false),
    SIXTY_THREE(63, false),
    SIXTY_FOUR(64, false),
    SIXTY_FIVE(65, false),
    SIXTY_SIX(66, false),
    SIXTY_SEVEN(67, true),
    SIXTY_EIGHT(68, false),
    SIXTY_NINE(69, false),
    SEVENTY(70, false),
    SEVENTY_ONE(71, true),
    SEVENTY_TWO(72, false),
    SEVENTY_THREE(73, true),
    SEVENTY_FOUR(74, false),
    SEVENTY_FIVE(75, false),
    SEVENTY_SIX(76, false),
    SEVENTY_SEVEN(77, false),
    SEVENTY_EIGHT(78, false),
    SEVENTY_NINE(79, true),
    EIGHTY(80, false),
    EIGHTY_ONE(81, false),
    EIGHTY_TWO(82, false),
    EIGHTY_THREE(83, true),
    EIGHTY_FOUR(84, false),
    EIGHTY_FIVE(85, false),
    EIGHTY_SIX(86, false),
    EIGHTY_SEVEN(87, false),
    EIGHTY_EIGHT(88, false),
    EIGHTY_NINE(89, true),
    NINETY(90, false),
    NINETY_ONE(91, false),
    NINETY_TWO(92, false),
    NINETY_THREE(93, false),
    NINETY_FOUR(94, false),
    NINETY_FIVE(95, false),
    NINETY_SIX(96, false),
    NINETY_SEVEN(97, true),
    NINETY_EIGHT(98, false),
    NINETY_NINE(99, false),
    ONE_HUNDRED(100, false);

    final int number;
    final boolean isGreatNumber;

    Numbers(int number, boolean isGreatNumber) {
        this.number = number;
        this.isGreatNumber = isGreatNumber;
    }
}
